### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rendalu** [ramandv/obsidian-snippets-manager#1]
Could this be updated to allow snippets to be organized as multiple notes inside of a particular directory?

i.e.

Snippets/
Snippets1.md (one or more snippets)
Snippets2.md (one or more snippets)

If someone has a lot of snippets, keeping everything in a single file is kind of counter to the idea of Obsidian.

In any case, great work!  Love the plugin!

**Comment by ramandv** [comment]
@rendalu Thanks for the suggestion. 
Feature has been added in v1.0.1. Update and check it out.
