### ISSUE TITLE
Capability to fetch Snippets from sub-folder

### ISSUE THREAD

**Issue by PKDmeDEV** [ramandv/obsidian-snippets-manager#4]
Hi,
As it is a good practice to organize snippets in subfolders. Currently, the plugin picks up snippets from the defined parent directory and generates alfred-snippets.json. It will be amazing we can fetch snippets from sub-folder.

Thanks

**Comment by daniel347x** [comment]
@PKDmeDEV - I need this too, so I've created a PR:

https://github.com/ramandv/obsidian-snippets-manager/pull/5

**Comment by ramandv** [comment]
Thanks @daniel347x . New version released 1.1.1
